name: ❌ Bug report
description: Report errors or unexpected behavior
labels: ❌ bug
body:
- type: checkboxes
  attributes:
      label: 🧐 Have you read the FAQ and viewed similar issues?
      description: <strong>❗️❗️ Important:</strong> Please review the <a href="https://github.com/JaimeTR/spotifypremium#faq">FAQ</a> and check both open and closed <a href="https://github.com/JaimeTR/spotifypremium/issues">issues</a>, as your concern may have already been addressed.
      options:
        - label: I have read the FAQ
          required: true
        - label: I have checked older issues, open and closed
          required: true
        - label: I did a clean install of SpotifyPremium as described in the FAQ
          required: true  
- type: markdown
  attributes:
    value: "###"    
- type: input
  id: lang_spoti
  attributes:
    label: Сountry of your account
    description: You can view your country on your account page, in paragraph <a href="https://www.spotify.com/account/profile/">Country or region</a>.
    placeholder: "e.g. Ukraine"
  validations:
    required: true 
- type: markdown
  attributes:
    value: "###"     
- type: dropdown
  id: plan
  attributes:
    label: What is your Spotify Plan?
    description: You can view your plan on your account page, under <a href="https://www.spotify.com/account/">Your plan</a>.
    options:
      - Free
      - Premium
  validations:
    required: true
- type: markdown
  attributes:
    value: "###"        
- type: dropdown
  id: spicetify
  attributes:
    label: Do you have Spicetify installed?
    description: <a href="https://spicetify.app/">Spicetify</a> is a command line tool to customize Spotify client.
    options:
      - "No"
      - "Yes"
  validations:
    required: true
- type: markdown
  attributes:
    value: "###"       
- type: textarea
  attributes:
    label: ℹ Computer information
    description: |
      - Spotify: e.g. <kbd>1.1.90.859.gf1bb1e36</kbd> (Avoid labeling version as "latest" due to regional update variations in Spotify)
        - In the open Spotify client in the upper left corner, click <kbd>•••</kbd> → <kbd>Help</kbd> → <kbd>About Spotify</kbd>
      - Windows: e.g. <kbd>Windows 11 21H2 22000.527</kbd> 
        - Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> to open the page to copy from.
      - PowerShell: e.g. <kbd>5.1.19041.1200</kbd>
        - Press <kbd>Win</kbd> + <kbd>R</kbd> then type "powershell," and press <kbd>Enter</kbd>, type the following command <kbd>Get-Host | Select-Object Version</kbd>
    placeholder: |
        - Spotify: 
        - Windows: 
        - PowerShell:  
    value: |
        - Spotify: 
        - Windows: 
        - PowerShell: 
    render: markdown   
  validations:
    required: true    
- type: textarea
  attributes:
    label: 📝 Description
    description: List steps to reproduce the error and details on what happens and what you expected to happen.
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: 📸 Screenshots
    description: Place any screenshots of the issue here if needed
  validations:
    required: false    
    
